name: back-build-push

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create image tag
      run: echo "IMAGE_TAG=ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-infrastructure/example-back:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the image
      run: docker build --file example-backend/HttpApi/Dockerfile --tag ${{ env.IMAGE_TAG }} example-backend
    - name: Login the registry
      run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
    - name: Push the image
      run: docker push ${{ env.IMAGE_TAG }}
    - name: Logout from the registry
      run: docker logout
